---
title: 1
description: 
published: true
date: 2022-09-18T05:19:49.068Z
tags: 
editor: markdown
dateCreated: 2022-09-18T05:19:46.486Z
---

Flexget has crashed once a day for the last 5 days. I have the daemon running.

Flexget version: 2.20.10

Windows 7

Crash log: https://pastebin.com/6dxFLSn6

Config.yml: https://pastebin.com/UvjMGY58


```
2019-03-08 04:52 CRITICAL task          purge-movies-queue BUG: Unhandled error in plugin filesystem: timestamp out of range for platform localtime()/gmtime() function
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 522, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\input\filesystem.py", line 225, in on_task_input
    path_list, match, recursive, test_mode, get_files, get_dirs, get_symlinks
  File "c:\python27\lib\site-packages\flexget\plugins\input\filesystem.py", line 201, in get_entries_from_path
    entry = self.create_entry(path_object, test_mode)
  File "c:\python27\lib\site-packages\flexget\plugins\input\filesystem.py", line 142, in create_entry
    entry['created'] = datetime.fromtimestamp(filepath.getctime())
ValueError: timestamp out of range for platform localtime()/gmtime() function
```
